### ISSUE TITLE
Determine color scheme

### ISSUE THREAD

**Issue by corymcdonald** [CoryMcDonald/Procurable#19]
Develop a color scheme for the application

**Comment by lbdorrou** [comment]
![image](https://cloud.githubusercontent.com/assets/5875320/12906972/78b39212-ceab-11e5-8745-026ad3ccf6ce.png)

**Comment by lbdorrou** [comment]
Bright Red - #F44336
Dark Red - #A90F03
Pink - #FF8F86
Dark Grey - #232323
Off White - #F4F4F4
Tiffany Blue - #A0D9D9
